@startuml

entity User{
    id: string
    username: string
    password: string
    point: number
}

entity Admin{
    id: string
    username: string
    password: string
    point: number
}



entity Game {
    id: string
    name: string
    start_time: datetime
    end_time: datetime
    winner: Player
}

entity Player {
    id: string
    name: string
}

entity Piece {
    id: int
    type: string
    color: string
    position: Position
}

entity Position {
    x: number
    y: number
}
User ||--o{ Game
Admin||--o{ Game
Game||--|{ Player
Game||--|{ Piece
Piece ||--|| Position
User||--||Player



@enduml