@startuml

entity Game {
    id: string
    name: string
    start_time: datetime
    end_time: datetime
    winner: Player
}

entity Player {
    id: string
    name: string
}

entity Piece {
    id: int
    type: string
    color: string
    position: Position
}

entity Position {
    x: number
    y: number
}

Game||--|{ Player
Game||--|{ Piece
Piece ||--|| Position



@enduml