@startuml chessGame
left to right direction
actor "Player" as player
actor "System" as system

rectangle ChessGame {
    ' player
    usecase "Sign in" as signIn
    usecase "Sign up" as signUp
    usecase "Start game" as startGame
    usecase "Resign" as resign
    usecase "Move piece" as movePiece
    ' usecase "Check" as Check

    ' system 
    usecase "Timeout" as timeout
    ' usecase "Game result" as gameResult
    usecase "Validate move" as validateMove
    usecase "Show move history" as showMoveHistory
    usecase "Checkmate" as checkmate
}

player --> signIn
player --> signUp
player --> startGame
player --> resign
player --> movePiece
player --> Check

system --> timeout
' system --> gameResult
system --> validateMove
system --> showMoveHistory
system --> checkmate


@enduml



