@startuml



start
:Click any position;
:Remove highlight other position;
if(piece?) then (yes)
    :highlight this position;
    :handle show valid move;
else (no)
    stop
endif

:click in highlight position;

if (isCheck) then (yes)
    split
        :sử lý bị chiếu;
    endsplit
else (no)
    if(position can move have piece) then (yes)
        :capture;
    else (no)
        :move;
    endif
endif
:disable bên vừa đi;
end
@enduml