@startuml
title chessGame
class User {
    -id: string
    -username: string
    -password: string
    -point: number

    startGame()
    leaveGame()
    resetGame()
    resign()

    createAccount()
    deleteAccount()
    updateAccount()

}

class Admin {
    id: string
    username: string
    password: string

    deleteAccount()
    updateAccount()
    blockAccount()

}


enum PieceName{
    Pawn
    Queen
    King
    Rock
    Bishop
    Knight
}



class Piece {
    name: PieceName
    color: string
    position: string
    isCaptured: boolean
    isChecked: boolean


    pick()
    move()
    checkRuleMove()

}


class Pawn as "pawn"{
    promote()
}

class Queen as "queen"{
}

class King as "king"{
    isCastling

    castling()
}

class Rock as "rock"{
    isCastling

    castling()
}

class Bishop as "bishop"{
}

class Knight as "knight"{
}

Piece <|-- Pawn
Piece <|-- Queen
Piece <|-- King
Piece <|-- Rock
Piece <|-- Bishop
Piece <|-- Knight




@enduml