@startuml chessGame
title Chess game

start
:Start;
if (Have account ?) then (no)
  :Signup;
  :Login;
else (yes)
  :Login;
endif
:Homepage;
:Start chess game;
:Render chess board;
:Move piece;
if (Invalid move ?) then (yes)
  :Show warning can not move;
  :Choose another move;
else (no)
endif
:Who's next?;
if (isChecked) then (yes)
  if (Checkmate ?) then (yes)
    :End game;
    :Caculate result;
    :Play again or Exit?;
  else (no)
    :Continue playing;
  endif
else (no)
  :Continue playing;
endif
stop
@enduml