@startuml chess

left to right direction
actor Player as player
actor System as system

package ChessGame {
    usecase (Start game) as start
    usecase (End game) as end
    usecase (Restart game) as restart
    usecase (Flip board) as flip
    usecase (Move piece) as move
    usecase (Exit game) as exit
    usecase (Draw) as draw
    usecase (Win) as win
    usecase (Lose) as lose
    usecase (Result) as result
    usecase (Promote Pawn) as promote
    usecase (Take piece) as take
    usecase (Check) as check
    usecase (CheckMate) as mate
    usecase (Resign) as resign
    usecase (Time out) as time
}

player ---> start
start --> restart
start --> flip
start --> move
start --> exit
start --> resign
move --> check
move --> promote
move --> take
promote --> move
take --> check
take --> move
take --> mate
check --> mate
check --> move
mate --> end
end --> result
result --> draw
result --> win
result --> lose
resign --> lose
result <--- system
time <-- system

@enduml