import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './styles/style.css'
import styles from './rootLayout.module.css'
import Link from 'next/link'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"; 
import { config } from "@fortawesome/fontawesome-svg-core";
import { faChessBoard, faEllipsisVertical } from '@fortawesome/free-solid-svg-icons'
import Header from './components/header'
config.autoAddCss = false; 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <body className={inter.className}>
          <header className={styles.header}>
            <Link href="./main" style={{textDecoration: "none"}}>
              <FontAwesomeIcon icon={faChessBoard} className={styles.logoChessGame} />
            </Link>
            <div className={styles.nav}>
                <Link className={styles.navAccounts} href="./login" >Login</Link>
                <Link className={styles.navAccounts} href="./signup" >Sign up</Link>
                <FontAwesomeIcon icon={faEllipsisVertical} className={styles.navAccounts} />
            </div>
        </header>

        {children}
        
        <footer className={styles.footer}>
             <h1 className={styles.footerCreate}>By team 1 SET 2023</h1>
        </footer>
      </body>
    </html>
  )
}
